#! /usr/bin/env bash

#case "$(echo ${0##*/} | sed -n 's/-linux-.*//p')" in
#	mips)	;;
#	i686)	;;
#	arm)	;;
#	"")	;;
#	*)	;;
#esac

TARGET_TOOLCHAIN_STAGING_DIR="${GLOBAL_LIBDIR%/usr/lib}"
export PKG_CONFIG_DIR=""
export PKG_CONFIG_SYSTEM_LIBRARY_PATH="${TARGET_TOOLCHAIN_STAGING_DIR}/usr/lib"
export PKG_CONFIG_SYSTEM_INCLUDE_PATH="${TARGET_TOOLCHAIN_STAGING_DIR}/usr/include"
export PKG_CONFIG_LIBDIR="${TARGET_TOOLCHAIN_STAGING_DIR}/usr/lib/pkgconfig"
PKG_CONFIG_PATH="$PKG_CONFIG_LIBDIR"

exec ${0%/*}/pkgconf "$@"

