#! /usr/bin/env bash

case "$(echo ${0##*/} | sed -n 's/-linux-.*//p')" in
	mips)	SETPCVS="mips"		;;
	i686)	SETPCVS="i686"		;;
	arm)	SETPCVS="arm"		;;
	"")	SETPCVS="no"		;;
	*)	SETPCVS="unknown"	;;
esac

if [ "$SETPCVS" != "no" ]; then
	TARGET_TOOLCHAIN_STAGING_DIR="${GLOBAL_LIBDIR%/usr/lib}"
	export PKG_CONFIG_LIBDIR="${TARGET_TOOLCHAIN_STAGING_DIR}/usr/lib/pkgconfig"
else
	MDPWD="$(dirname $(realpath $0))"
	TARGET_TOOLCHAIN_STAGING_DIR="$(realpath $MDPWD/..)"
	export PKG_CONFIG_LIBDIR="${TARGET_TOOLCHAIN_STAGING_DIR}/usr/lib64/pkgconfig:${TARGET_TOOLCHAIN_STAGING_DIR}/usr/lib/pkgconfig:${PKG_CONFIG_LIBDIR}"
fi

export PKG_CONFIG_DIR=""
export PKG_CONFIG_SYSTEM_LIBRARY_PATH="${TARGET_TOOLCHAIN_STAGING_DIR}/usr/lib"
export PKG_CONFIG_SYSTEM_INCLUDE_PATH="${TARGET_TOOLCHAIN_STAGING_DIR}/usr/include"
export PKG_CONFIG_PATH="$PKG_CONFIG_LIBDIR"

exec ${0%/*}/pkgconf "$@"

