$(call PKG_INIT_BIN, 1.7.3)
$(PKG)_SOURCE:=getdns-$($(PKG)_VERSION).tar.gz
$(PKG)_HASH:=f1404ca250f02e37a118aa00cf0ec2cbe11896e060c6d369c6761baea7d55a2c
$(PKG)_SITE:=https://getdnsapi.net/dist,https://getdnsapi.net/releases/getdns-$(subst .,-,$($(PKG)_VERSION))
### WEBSITE:=https://www.getdnsapi.net/
### MANPAGE:=https://dnsprivacy.org/dns_privacy_daemon_-_stubby/
### CHANGES:=https://github.com/getdnsapi/getdns/releases
### CVSREPO:=https://github.com/getdnsapi/getdns

$(PKG)_BINARY:=$($(PKG)_DIR)/stubby/stubby
$(PKG)_TARGET_BINARY:=$($(PKG)_DEST_DIR)/usr/bin/stubby

$(PKG)_DEPENDS_ON += openssl
$(PKG)_DEPENDS_ON += yaml

$(PKG)_CONFIGURE_OPTIONS += -DBUILD_DOXYGEN=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_EXAMPLES=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_TESTING=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_LIBEVENT2=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_LIBEV=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_LIBUV=OFF
#$(PKG)_CONFIGURE_OPTIONS += -DPATH_TRUST_ANCHOR_FILE="/tmp/flash/unbound/root.key"
#$(PKG)_CONFIGURE_OPTIONS += -DLIBUNBOUND_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"
#$(PKG)_CONFIGURE_OPTIONS += -DLIBEV_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"
#$(PKG)_CONFIGURE_OPTIONS += -DLIBUV_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"
$(PKG)_CONFIGURE_OPTIONS += -DLIBYAML_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"
$(PKG)_CONFIGURE_OPTIONS += -DOPENSSL_INCLUDE_DIR="$(TARGET_TOOLCHAIN_STAGING_DIR)/usr"
$(PKG)_CONFIGURE_OPTIONS += -DUSE_GNUTLS=OFF
$(PKG)_CONFIGURE_OPTIONS += -DUSE_LIBIDN2=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_STUB_ONLY=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_STUBBY=ON
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_GETDNS_QUERY=OFF
$(PKG)_CONFIGURE_OPTIONS += -DBUILD_GETDNS_SERVER_MON=OFF
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_STATIC=ON
$(PKG)_CONFIGURE_OPTIONS += -DENABLE_SHARED=OFF
$(PKG)_CONFIGURE_OPTIONS += -DCMAKE_SKIP_RPATH=YES


$(PKG_SOURCE_DOWNLOAD)
$(PKG_UNPACKED)
$(PKG_CONFIGURED_CMAKE)

$($(PKG)_BINARY): $($(PKG)_DIR)/.configured
	$(SUBMAKE) -C $(GETDNS_DIR)
#cmake	cd $(GETDNS_DIR) && cmake -LA .

$($(PKG)_TARGET_BINARY): $($(PKG)_BINARY)
	$(INSTALL_BINARY_STRIP)

$(pkg):

$(pkg)-precompiled: $($(PKG)_TARGET_BINARY)


$(pkg)-clean:
	-$(SUBMAKE) -C $(GETDNS_DIR) clean
	$(RM) $(GETDNS_DIR)/.configured

$(pkg)-uninstall:
	$(RM) $(GETDNS_TARGET_BINARY)

$(PKG_FINISH)
