#! /usr/bin/env bash
KERNEL_CONFIG="${1:-.}/.config"
FREETZ_CONFIG="${FREETZ_BASE_DIR:-.}/.config"
MODULE_CONFIG="$(sed -rn "s/^FREETZ_MODULE_(.*)=y$/\1/p" "$FREETZ_CONFIG")"

koon() {
	local arg="$1"
	shift
	[ $# -gt 0 ] && koon "$@"

	local state="m"
	if [ "$arg" == "${arg/=}" ]; then
		grep -q "^CONFIG_$arg=y$" "$KERNEL_CONFIG" && echo "#### Fail, kernel builtin: $arg" && return
		grep -q "^CONFIG_$arg=m$" "$KERNEL_CONFIG" && echo "#### Skip, already module: $arg" && return
	else
		grep -q "^CONFIG_${arg}$" "$KERNEL_CONFIG" && echo "#### Skip, yet as desired: $arg" && return
		state="${arg#*=}"
	fi

	sed -i "/^CONFIG_$arg=/d;/^# CONFIG_$arg /d;\$aCONFIG_$arg=$state" "$KERNEL_CONFIG"
	echo "#### Done, changed symbol: $arg"
}

for kmod in $MODULE_CONFIG; do
	case "$kmod" in
		block2mtd)		koon  MTD_BLOCK2MTD		MTD ;;
		aead)			koon  CRYPTO_AEAD		 ;;
		arc4)			koon  CRYPTO_ARC4		 ;;
		aes)			koon  CRYPTO_AES		 ;;
		cbc)			koon  CRYPTO_CBC		 ;;
		crypto_blkcipher)	koon  CRYPTO_BLKCIPHER		 ;;
		crypto_hash)		koon  CRYPTO_HASH		 ;;
		crypto_wq)		koon  CRYPTO_WORKQUEUE		 ;;
		cryptomgr)		koon  CRYPTO_MANAGER		 ;;
		rng)			koon  CRYPTO_ANSI_CPRNG		 ;;
		sha1)			koon  CRYPTO_SHA1		 ;;
		sha1_generic)		koon  CRYPTO_SHA1		 ;;
		sha256)			koon  CRYPTO_SHA256		 ;;
		sha256_generic)		koon  CRYPTO_SHA256		 ;;
		pcompress)		koon  CRYPTO_PCOMP		 ;;
		bfusb)			koon  BT_HCIBFUSB		BT ;;
		btusb)			koon  BT_HCIBTUSB		BT BT_HCIBTUSB_RTL=y BT_HCIUART_INTEL=y ;;
		btintel)		koon  BT_INTEL			BT ;;
		btbcm)			koon  BT_HCIBCM203X		BT ;;
		btrtl)			koon  BT_RTL 			BT ;;
		capiconn)		koon  ISDN_CAPI_CAPICONN	 ;;
		cdrom)			koon  CDROM			 ;;
		dummy)			koon  DUMMY			 ;;
		dm_mod)			koon  BLK_DEV_DM		MD=y ;;
		dm_crypt)		koon  DM_CRYPT			 ;;
		firmware_class)		koon  FW_LOADER			 ;;
		hci_usb)		koon  BT_HCIUSB			BT ;;
		loop)			koon  BLK_DEV_LOOP		BLK_DEV=y ;;
		nand)			koon  MTD_NAND			 ;;
		musb_hdrc)		koon  USB_MUSB_HDRC		 ;;
		nbd)			koon  BLK_DEV_NBD		 ;;
		ohio_nand)		koon  MTD_NAND_OHIO		 ;;
		scsi_mod)		koon  SCSI			 ;;
		sd_mod)			koon  BLK_DEV_SD		 ;;
		sg)			koon  CHR_DEV_SG		 ;;
		slhc)			koon  PPP			 ;;
		sr_mod)			koon  BLK_DEV_SR		BLK_DEV_SR_VENDOR=n ;;
		usb_storage)		koon  USB_STORAGE		 ;;
		usbcore)		koon  USB			 ;;
		usbip)			koon  USBIP_CORE		 ;;
		usbip_common_mod)	koon  USB_IP_COMMON		STAGING=y STAGING_EXCLUDE_BUILD=n ;;
		usblp)			koon  USB_PRINTER		 ;;
		usbmon)			koon  USB_MON			 ;;
		ppp_generic)		koon  PPP			 ;;
		ppp_async)		koon  PPP_ASYNC			PPP ;;
		ppp_deflate)		koon  PPP_DEFLATE		PPP ;;
		ppp_mppe)		koon  PPP_MPPE			PPP ;;
		ppp_mppe_mppc)		koon  PPP_MPPE_MPPC		PPP ;;
		pppoe)			koon  PPPOE			PPP ;;
		pppox)			koon  PPPOX			PPP ;;
		ch341)			koon  USB_SERIAL_CH341		 ;;
		cp2101)			koon  USB_SERIAL_CP2101		 ;;
		cp210x)			koon  USB_SERIAL_CP210X		 ;;
		ftdi_sio)		koon  USB_SERIAL_FTDI_SIO	 ;;
		ipaq)			koon  USB_SERIAL_IPAQ		 ;;
		option)			koon  USB_SERIAL_OPTION		 ;;
		pl2303)			koon  USB_SERIAL_PL2303		 ;;
		usbserial)		koon  USB_SERIAL		 ;;
		ext2)			koon  EXT2_FS			 ;;
		ext3)			koon  EXT3_FS			 ;;
		jbd)			koon  JBD			 ;;
		mbcache)		koon  FS_MBCACHE		 ;;
		crc16)			koon  CRC16			 ;;
		ext4)			koon  EXT4_FS			 ;;
		jbd2)			koon  JBD2			 ;;
		fat)			koon  FAT_FS			 ;;
		vfat)			koon  VFAT_FS			 ;;
		hfs)			koon  HFS_FS			MISC_FILESYSTEMS=y ;;
		hfsplus)		koon  HFSPLUS_FS		MISC_FILESYSTEMS=y ;;
		iso9660)		koon  ISO9660_FS		 ;;
		jffs2)			koon  JFFS2_FS			 ;;
		mini_fo)		koon  MINI_FO			 ;;
		minix)			koon  MINIX_FS			MISC_FILESYSTEMS=y ;;
		msdos)			koon  MSDOS_FS			 ;;
		reiserfs)		koon  REISERFS_FS		 ;;
		udf)			koon  UDF_FS			 ;;
		unionfs)		koon  UNION_FS			 ;;
		autofs4)		koon  AUTOFS4_FS		 ;;
		cifs)			koon  CIFS			NETWORK_FILESYSTEMS=y CIFS_DEBUG=n ;;
		des_generic)		koon  CRYPTO_DES		 ;;
		cmac)			koon  CRYPTO_CMAC		 ;;
		ecb)			koon  CRYPTO_ECB		 ;;
		hmac)			koon  CRYPTO_HMAC		 ;;
		md4)			koon  CRYPTO_MD4		 ;;
		md5)			koon  CRYPTO_MD5		 ;;
		coda)			koon  CODA_FS			NETWORK_FILESYSTEMS=y ;;
		fuse)			koon  FUSE_FS			 ;;
		lockd)			koon  LOCKD			 ;;
		grace)			koon  GRACE_PERIOD		 ;;
		sunrpc)			koon  SUNRPC			 ;;
		nfs)			koon  NFS_FS			NETWORK_FILESYSTEMS=y ;;
		nfsv2)			koon  NFS_V2			 ;;
		nfsv3)			koon  NFS_V3			 ;;
		nfsd)			koon  NFSD			NETWORK_FILESYSTEMS=y NFSD_V3=y ;;
		nls_cp437)		koon  NLS_CODEPAGE_437		 ;;
		nls_cp850)		koon  NLS_CODEPAGE_850		 ;;
		nls_iso8859_1)		koon  NLS_ISO8859_1		 ;;
		nls_iso8859_15)		koon  NLS_ISO8859_15		 ;;
		nls_utf8)		koon  NLS_UTF8			 ;;
		crc_ccitt)		koon  CRC_CCITT			 ;;
		tun)			koon  TUN			 ;;
		exportfs)		koon  EXPORTFS			 ;;
		lzo_compress)		koon  CRYPTO_LZO		 ;;
		lzo_decompress)		koon  CRYPTO_LZO		 ;;
		bluetooth)		koon  BT			 ;;
		bnep)			koon  BT_BNEP			BT_BREDR=y ;;
		l2cap)			koon  BT_L2CAP			 ;;
		rfcomm)			koon  BT_RFCOMM			BT_BREDR=y ;;
		cls_u32)		koon  NET_CLS_U32		NET_SCHED=y ;;
		sch_cbq)		koon  NET_SCH_CBQ		NET_SCHED=y ;;
		sch_htb)		koon  NET_SCH_HTB		NET_SCHED=y ;;
		sch_llq)		koon  NET_SCH_LLQ		NET_SCHED=y ;;
		sch_sfq)		koon  NET_SCH_SFQ		NET_SCHED=y ;;
		sch_tbf)		koon  NET_SCH_TBF		NET_SCHED=y ;;
		*)		echo "#### Warn, not configured: $kmod"	 ;;
	esac
done

exit 0

